group=net.lagerwey.plugins.cucumber.kotlin
platformType = IU
platformVersion = 2026.2.2

platformPlugins = org.jetbrains.plugins.yaml:262.10315.19,gherkin:262.8665.173
platformBundledPlugins = com.intellij.java,com.intellij.properties

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
kotlin.stdlib.default.dependency = false