group=net.lagerwey.plugins.cucumber.kotlin
platformType = IU
platformVersion = 2025.3.1

platformPlugins = org.jetbrains.plugins.yaml:253.29346.50,gherkin:253.28294.218
platformBundledPlugins = com.intellij.java

# Opt-out flag for bundling Kotlin standard library.
# See https://plugins.jetbrains.com/docs/intellij/kotlin.html#kotlin-standard-library for details.
kotlin.stdlib.default.dependency = false